/*
Package liveness provides a failure detecter (Fd), leader detector (Ld) and heartbeat
emitter (HbEm).

The failure detector algorithm is based on the eventually perfect failure detector algorithm
described in the Introduction to Reliable and Secure Distributed Programming textbook.

The leader detector algorithm builds on the failure detector algorithm and is based on the
monarchical eventual leader detection algorithm also described in the aforementioned textbook.

The heartbeat emitter algorithm emits heartbeats to the other replicas in the system based on
a periodic timeout generated by a Ticker.
*/
package liveness
