// generated by stringer -type=Type; DO NOT EDIT

package event

import "fmt"

const _Type_name = "UnknownStartRunningProcessingShutdownStartExitThroughputSampleInitListeningInitTransferStartInitTransferDoneInitInitializedLRWaitForActivationLRActivatedReconfigFirstSlotReceivedReconfigJoinedFailureHandlingSuspectFailureHandlingInitStartFailureHandlingInitDoneCatchUpMakeReqCatchUpSentReqCatchUpRecvReqCatchUpSentRespCatchUpRecvRespCatchUpDoneHandlingRespLRStartLRPrepareEpochSentLRPrepareEpochRecvLRActivatedFromPELRPreConnectSleepReconfigStartReconfigProposeReconfigExecReconfCmdReconfigDoneARecStartARecRMSentARecStopPaxosARecActivatedFromCPsARecRestartClientRequestLatency"

var _Type_map = map[Type]string{
	0:  _Type_name[0:7],
	1:  _Type_name[7:12],
	2:  _Type_name[12:19],
	3:  _Type_name[19:29],
	4:  _Type_name[29:42],
	5:  _Type_name[42:46],
	16: _Type_name[46:62],
	24: _Type_name[62:75],
	25: _Type_name[75:92],
	26: _Type_name[92:108],
	27: _Type_name[108:123],
	32: _Type_name[123:142],
	33: _Type_name[142:153],
	40: _Type_name[153:178],
	41: _Type_name[178:192],
	48: _Type_name[192:214],
	49: _Type_name[214:238],
	50: _Type_name[238:261],
	56: _Type_name[261:275],
	57: _Type_name[275:289],
	58: _Type_name[289:303],
	59: _Type_name[303:318],
	60: _Type_name[318:333],
	61: _Type_name[333:356],
	64: _Type_name[356:363],
	65: _Type_name[363:381],
	66: _Type_name[381:399],
	67: _Type_name[399:416],
	68: _Type_name[416:433],
	72: _Type_name[433:446],
	73: _Type_name[446:461],
	74: _Type_name[461:482],
	75: _Type_name[482:494],
	80: _Type_name[494:503],
	81: _Type_name[503:513],
	82: _Type_name[513:526],
	83: _Type_name[526:546],
	84: _Type_name[546:557],
	88: _Type_name[557:577],
}

func (i Type) String() string {
	if str, ok := _Type_map[i]; ok {
		return str
	}
	return fmt.Sprintf("Type(%d)", i)
}
